version: "3.7"

services:
  db:
    image: "postgres:alpine"
    container_name: db
    env_file: ./.env
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3030:3030"
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
